### PR TITLE
Update Robot Tools, WPILib and syntax

### PR DESCRIPTION
**Pull request by owenflatman**

### CODE REVIEW

**Comment by legoguy1000** [comment]
Why are we removing this?

**Comment by owenflatman** [comment]
So it can build even tho we have motors and components not under io

**Comment by wilsonwatson** [comment]
Looking at it, everything is behind IO. I think the issue is that it pulls from "main" in RobotTools, which has changed a bit since we added it to this repo.

**Comment by legoguy1000** [comment]
We either need to use a specific tag or just fix it to work with the changes. All the other project s will be similar

**Review by legoguy1000 — APPROVED** [review]

**Review by wilsonwatson — APPROVED** [review]

**Pull request merged**
